### ISSUE TITLE
Wat als een browser CSS Transforms niet ondersteunt?

### ISSUE THREAD

**Issue by krijnhoetmer** [tijsluitse/browser-technologies#2]
Bijvoorbeeld IE8 (of IE9 in dit geval). Pas op met dingen op z'n plek zetten met transforms (het centreren van `section` in jouw voorbeeld).

**Comment by tijsluitse** [comment]
Ik heb nu alles geprefixed

**Comment by krijnhoetmer** [comment]
Wat lost dat op?
