### ISSUE TITLE
Melding bij showFallback

### ISSUE THREAD

**Issue by krijnhoetmer** [tijsluitse/browser-technologies#3]
Op een aantal plekken spring je naar `showFallback()` waar "U kan helaas geen notificaties ontvangen." getoond wordt. Op zich netjes met feature detection, maar probeer je te verplaatsen in de gebruiker, en niet vanuit de techniek te denken. Kun je het concept "notificatie" niet op een totaal andere manier implementeren? In plaats van de gebruiker straffen met een "dit kan niet, helaas". Ik lees zo'n melding meer als "Ik als ontwerper/ontwikkelaar kon helaas op geen andere manier iets nuttigs voor je maken" (en in mijn hoofd zie ik dan ook een middelvinger erbij :).

**Comment by tijsluitse** [comment]
Ik heb deze melding vervangen door de vraag of mensen op de hoogte gehouden willen worden over de stand via email.

**Comment by krijnhoetmer** [comment]
Mjah, is dat echt de meest gebruiksvriendelijke oplossing die je kunt bouwen? :) Of is het het makkelijkste wat je kunt doen?
