### ISSUE TITLE
Demo gebruikt nu alleen timeouts voor nieuwe scores

### ISSUE THREAD

**Issue by krijnhoetmer** [tijsluitse/browser-technologies#4]
De nieuwe scores "bestaan" dus ook alleen in JavaScript. We hebben het hier al eerder over gehad, maar waarom gebruik je je HTML laag niet als dé plek om die scores uit te halen (en als notificatie o.i.d. te tonen)? Aanname hierbij is dat "de server" die dynamische HTML genereert, maar dat kun je faken, volgens mij.

**Comment by krijnhoetmer** [comment]
Sorry, ik zie nu pas de 2.html en 3.html. Probeer die twee bestanden ook te gebruiken in je demo. Op die manier fake je een server die 'nieuwe scores' beschikbaar heeft. Laat de eerste pagina bijvoorbeeld de tweede laden, en die de derde. Dat is een natuurlijk verloop van een wedstrijd. JavaScript kan dat dan overnemen en verrijken met een notificatie, bijvoorbeeld.

**Comment by tijsluitse** [comment]
Hey Krijn, ik heb nu een http equiv toegevoegd waarmee hij zonder js door de scores/verschillende pagina's heen gaat

**Comment by tijsluitse** [comment]
staat online op http://tijsluitse.com/fas2025

**Comment by krijnhoetmer** [comment]
Ok, en nu?

**Comment by tijsluitse** [comment]
Nu kun je de score volgen (gefaked) wanneer er geen js beschikbaar is, en is het enhancement met js dat je notificaties kan krijgen

**Comment by krijnhoetmer** [comment]
Volgens mij niet. Test het even in verschillende scenario's ajb.

**Comment by tijsluitse** [comment]
Hey Krijn, Ik zou graag willen weten wat ik nou precies moet aanpassen want volgens mij begrijp ik je niet.

**Comment by krijnhoetmer** [comment]
Ik snap je demo nu helemaal niet meer. Zit te kijken op http://tijsluitse.com/browser-technologies/ maar volgens mij is 'ie stuk.

**Comment by tijsluitse** [comment]
Het staat online!

**Comment by krijnhoetmer** [comment]
Hij gebruikt alleen nog steeds timeouts :)

Iets concreter: stel dat er nog een stand bij komt en ik wil alleen de HTML aanpassen. Kan dat nu?

**Comment by KoopReynders** [comment]
'mooier' oplossen: Kun je de http-equiv="refresh" gebruiken om ook in javascript het volgende file te pakken? En na hoeveel tijd het volgende file geladen moet worden?

**Comment by tijsluitse** [comment]
KRIJN EN KOOP HET IS GELUKT!! TOCH TOCH TOCH??

**Comment by KoopReynders** [comment]
Ja. Update je readme nog even met je 'nieuwe' PE opbouw.

**Comment by tijsluitse** [comment]
Yes done!

**Comment by KoopReynders** [comment]
https://docs.google.com/spreadsheets/d/1yK8r0hWDVfpvxcIJWEd8tqpk7ykbO2VcYwS2Ruwd2A8/edit#gid=0
