### ISSUE TITLE
Data updaten

### ISSUE THREAD

**Issue by KoopReynders** [tijsluitse/browser-technologies#5]
> Wat doe je als er data dynamisch binnenkomt. Dit moet je laten zien? Niet in 3 losse, maar in 1 demo,

**Comment by tijsluitse** [comment]
maar dit hebben jullie letterlijk gezegd dat het desnoods 3 losse html files zijn waar je doorheen gaat.. ik kan dit niet anders faken want ik weet niet hoe ik een aparte server of iets dergelijks moet maken.

**Comment by KoopReynders** [comment]
Op deze manier kunnen we niet zien of PE begrijpt en kan coden. Dus je zult toch een oplossing moeten bedenken voor hoe data verandert en dynamisch binnenkomt, zodat je demo daar op kan reageren.

**Comment by tijsluitse** [comment]
Oke ik snap dan toch niet hoe ik dit moet oplossen en waarom ik het niet begrijp. Hoe hebben anderen dit opgelost dan?

**Comment by tijsluitse** [comment]
CLOSING
